ELASTIC_HOST = "https://<ELASTICSEARCH_HOST>:9200"
ELASTIC_USER = "<ELASTIC_USERNAME>"
ELASTIC_PASSWORD = "<ELASTIC_PASSWORD>"

RAW_INDEX_NAME = "winlogbeat-indexname"
ANOMALY_INDEX_NAME = "ueba-anomalies"

N8N_WEBHOOK_PRODUCTION_URL = "http://<N8N_HOST>:5678/webhook/<WEBHOOK_ID>"

VERIFY_CERTS = False