input {
  beats {
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => ["https://<ELASTICSEARCH_HOST>:9200"]
    user => "<ELASTIC_USERNAME>"
    password => "<ELASTIC_PASSWORD>"
    ssl_enabled => true
    ssl_verification_mode => "none"
    index => "winlogbeat-nileuniversity"
  }
}